# Generated by Django 5.1.5 on 2025-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcycle",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="condition",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
