# Generated by Django 5.1.5 on 2025-02-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelcommitment",
            options={"ordering": ["objective", "level", "work_cycle"]},
        ),
    ]
