# Generated by Django 5.1.5 on 2025-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectobjectivecondition",
            options={"ordering": ["project", "objective", "condition"]},
        ),
        migrations.AddConstraint(
            model_name="projectobjectivecondition",
            constraint=models.UniqueConstraint(
                fields=("project", "objective", "condition"),
                name="unique_project_objective_condition",
            ),
        ),
    ]
