# Generated by Django 5.1.5 on 2025-02-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0002_objective_description"),
        ("projects", "0002_alter_projectobjectivecondition_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="levelcommitment",
            name="unique_level_attributes",
        ),
        migrations.RemoveField(
            model_name="levelcommitment",
            name="projectobjective",
        ),
        migrations.RemoveField(
            model_name="projectobjective",
            name="work_cycles",
        ),
        migrations.AddField(
            model_name="levelcommitment",
            name="objective",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="framework.objective",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="levelcommitment",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="levelcommitment",
            constraint=models.UniqueConstraint(
                fields=("project", "objective", "work_cycle", "level"),
                name="unique_level_attributes",
            ),
        ),
    ]
