# Generated by Django 5.1.5 on 2025-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("framework", "0002_alter_workcycle_options_alter_condition_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="name",
            field=models.TextField(max_length=250),
        ),
    ]
